import React from "react";

function ExportReport({ inventory = [] }) {
    
  const today = new Date().toLocaleDateString();
console.log("Export inventory:", inventory);
  const handleExportCSV = () => {
    const headers = ["Item Name", "Stock", "Threshold", "Risk Level"];

    const rows = inventory.map((item) => [
      item.itemName,
      item.currentStock,
      item.reorderThreshold,
      item.riskLevel
    ]);

    const csv =
      "data:text/csv;charset=utf-8," +
      [headers, ...rows].map((e) => e.join(",")).join("\n");

    const link = document.createElement("a");
    link.href = encodeURI(csv);
    link.download = "inventory_report.csv";
    link.click();
  };

  return (
    <div className="report-container">

      {/* HEADER */}
      <div className="report-header">
  <div>
    <h1>📦 StockGuard Inc.</h1>
    <p className="report-subtitle">Official Inventory Report</p>
    <p className="report-id">Report ID: INV-{Date.now()}</p>
  </div>

  <div className="report-meta">
    <p><strong>Date:</strong> {today}</p>
    <p><strong>Total Items:</strong> {inventory.length}</p>
    <p><strong>Status:</strong> Active</p>
  </div>
</div>



    {/* BUTTONS */}
    <div className="report-actions">
        <button onClick={() => window.print()}>
          Print / Save PDF
        </button>

        <button onClick={handleExportCSV}>
          Download CSV
        </button>
      </div>
      <h3>Inventory Overview</h3>

<div className="report-summary">
  <div>High Risk: {inventory.filter(i => i.riskLevel === "High").length}</div>
  <div>Medium Risk: {inventory.filter(i => i.riskLevel === "Medium").length}</div>
  <div>Low Risk: {inventory.filter(i => i.riskLevel === "Low").length}</div>
</div>

      {/* TABLE */}
      <table>
        <thead>
          <tr>
            <th>Item Name</th>
            <th> Current Stock</th>
            <th>Threshold</th>
            <th>Risk Level</th>
          </tr>
        </thead>

        <tbody>
          {inventory.map((item) => (
            <tr key={item._id}>
              <td>{item.itemName}</td>
              <td>{item.currentStock}</td>
              <td>{item.reorderThreshold}</td>
              <td className={`risk-${item.riskLevel.toLowerCase()}`}>
  {item.riskLevel}
</td>
            </tr>
          ))}
        </tbody>
      </table>
<div className="report-footer">
  <p>Generated by StockGuard System</p>
  <p>Confidential Business Report</p>
</div>
    </div>
  );
}

export default ExportReport;